### PR TITLE
Challenge 2 - Work & Co site headline check

### PR DESCRIPTION
**Pull request by milicazivanovic-work**
Cypress test to verify the headline on Work & Co site

### CODE REVIEW

**Comment by srdjadzogaz** [comment]
image
Looks good :)

**Comment by srdjadzogaz** [comment]
@milicazivanovic-work Can you just add in the Readme how to start the tests or project. 
It is a good practice/convention to do that.

**Review by srdjadzogaz — APPROVED** [review]

**Comment by milicazivanovic-work** [comment]
> @milicazivanovic-work Can you just add in the Readme how to start the tests or project. It is a good practice/convention to do that.

Will do, thanks!

**Comment by milicazivanovic-work** [comment]
@srdjadzogaz Added README file :)

**Comment by srdjadzogaz** [comment]
Cool, just go ahead and merge 🚀

**Pull request merged**
